---
Name: catalogueconfig
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - ilateral\SilverStripe\Orders\Extensions\AdminExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ilateral\SilverStripe\Catalogue\Extensions\SiteConfigExtension
SilverStripe\Framework\Controller\Controller:
  extensions:
    - ilateral\SilverStripe\Catalogue\Extensions\ControllerExtension
SilverStripe\Assets\Image:
  extensions:
    - ilateral\SilverStripe\Catalogue\Extensions\ImageExtension