---
Name: catalogueconfig
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverCommerce\CatalogueAdmin\Extensions\AdminExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\CatalogueAdmin\Extensions\SiteConfigExtension
SilverStripe\Framework\Controller\Controller:
  extensions:
    - SilverCommerce\CatalogueAdmin\Extensions\ControllerExtension
SilverStripe\Assets\Image:
  extensions:
    - SilverCommerce\CatalogueAdmin\Extensions\ImageExtension